apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mps-connect-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 900
      containers:
        - image: asia-southeast1-docker.pkg.dev/mpsconnect-cw-pilot/mps-connect/mps-connect-api:cloud-dev
          ports:
            - containerPort: 8000
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
          env:
            - name: API_KEY
              value: "mps-85-whampoa"
            - name: MODEL_DIR
              value: "/app/api/artifacts_zs_hier_plus"
            - name: PROVIDERS_JSON
              value: "/app/api/providers_map.json"
            - name: CORS_ORIGINS
              value: "https://mps-connect-web-987575541268.asia-southeast1.run.app"
            - name: GEMINI_API_KEY
              value: "AIzaSyAM3ykNjcF0clYJPaBqR_4a_7l-JGMTjV8"
            - name: MPLCONFIGDIR
              value: "/tmp"
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENVIRONMENT
              value: "production"
            - name: DATABASE_URL
              value: ""
            - name: HDB_API_KEY
              value: ""
            - name: MOM_API_KEY
              value: ""
            - name: MSF_API_KEY
              value: ""
            - name: IRAS_API_KEY
              value: ""
            - name: TRAFFIC_POLICE_API_KEY
              value: ""
            - name: JWT_SECRET_KEY
              value: "replace_me_with_secure_token"
            - name: ENCRYPTION_KEY
              value: "replace_me_with_secure_token"
