version: "3.9"

services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: mpsconnect_api
    volumes:
      - ../api/artifacts_zs_hier_plus:/app/artifacts_zs_hier_plus:ro
      - ../api/providers_map.json:/app/providers_map.json:ro
      - ../api/certs:/app/certs:ro
    environment:
      - MODEL_DIR=/app/artifacts_zs_hier_plus
      - PROVIDERS_JSON=/app/providers_map.json
    command: >
      uvicorn app:app
      --host 0.0.0.0
      --port 8000
      --ssl-certfile /app/certs/origin.pem
      --ssl-keyfile /app/certs/origin.key
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    container_name: mpsconnect_web
    ports:
      - "8080:80"
    restart: unless-stopped
