version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: mpsconnect_api
    volumes:
      - ../api:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    container_name: mpsconnect_web
    ports:
      - "8080:80"
    restart: unless-stopped
